# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/zynq_design/zynq_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design || ORIG_REF_NAME==zynq_design}]

# IP: bd/zynq_design/ip/zynq_design_processing_system7_0_0/zynq_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_processing_system7_0_0 || ORIG_REF_NAME==zynq_design_processing_system7_0_0}]

# IP: bd/zynq_design/ip/zynq_design_sha256_accel_axi_0_0/zynq_design_sha256_accel_axi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_sha256_accel_axi_0_0 || ORIG_REF_NAME==zynq_design_sha256_accel_axi_0_0}]

# IP: bd/zynq_design/ip/zynq_design_processing_system7_0_axi_periph_0/zynq_design_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==zynq_design_processing_system7_0_axi_periph_0}]

# IP: bd/zynq_design/ip/zynq_design_rst_processing_system7_0_100M_0/zynq_design_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==zynq_design_rst_processing_system7_0_100M_0}]

# IP: bd/zynq_design/ip/zynq_design_auto_pc_0/zynq_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_auto_pc_0 || ORIG_REF_NAME==zynq_design_auto_pc_0}]

# XDC: bd/zynq_design/ip/zynq_design_processing_system7_0_0/zynq_design_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_design_processing_system7_0_0 || ORIG_REF_NAME==zynq_design_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/zynq_design/ip/zynq_design_rst_processing_system7_0_100M_0/zynq_design_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==zynq_design_rst_processing_system7_0_100M_0}]

# XDC: bd/zynq_design/ip/zynq_design_rst_processing_system7_0_100M_0/zynq_design_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/zynq_design/ip/zynq_design_rst_processing_system7_0_100M_0/zynq_design_rst_processing_system7_0_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==zynq_design_rst_processing_system7_0_100M_0}]

# XDC: bd/zynq_design/ip/zynq_design_auto_pc_0/zynq_design_auto_pc_0_ooc.xdc

# XDC: bd/zynq_design/zynq_design_ooc.xdc
